### ISSUE TITLE
Błąd w tankowaniu

### ISSUE THREAD

**Issue by RaZoXzU** [Barto-Paja/iDocCar#19]
Można zatankować paliwem LPG pojazd z silnikiem ON  oraz można zatankować paliwem LPG  pojazd w którym wybrano tylko jeden zbiornik paliwa

**Comment by Barto-Paja** [comment]
Zrzut ekranu poproszę

**Comment by RaZoXzU** [comment]
![bez tytulu](https://user-images.githubusercontent.com/26406805/33809086-362a0d20-ddf1-11e7-9587-1dfe383e4b35.jpg)
![bez tytulu2](https://user-images.githubusercontent.com/26406805/33809087-3652a97e-ddf1-11e7-939d-17ca94da7497.jpg)

**Comment by RaZoXzU** [comment]
Dodatkowo wyszło że można zatankować więcej litrów niż pomieści bak xD

**Comment by Barto-Paja** [comment]
Ogarnę to niedługo xD
Chcę dokończyć te statystyki w r_cost xd

**Comment by RaZoXzU** [comment]
Ja dodaje wszystko co zauważę żeby nie zapomnieć, tak jak mówiłeś
xd

**Comment by Barto-Paja** [comment]
A mamy wgl. określaną pojemność baku?

**Comment by Barto-Paja** [comment]
dodaję jeszcze, że w tabeli fuel powinno rozdzielić w kolumnie tank na 0,1,2, ale na to już mam pomysł też

**Comment by Barto-Paja** [comment]
![fixed](https://user-images.githubusercontent.com/24964850/34650722-ee0eb758-f3c5-11e7-82ba-2c6d942acca0.jpg)

Zrobione 💃 😀
