### ISSUE TITLE
Nie można założyć konta 

### ISSUE THREAD

**Issue by MariuszMano** [Barto-Paja/iDocCar#24]
Nie da się założyć konta użytkownika. Wyskakuje jakiś błąd tworzenia konta SQL Mysql

**Comment by Barto-Paja** [comment]
Link do łatki: https://drive.google.com/open?id=1JbtoRwwutXq_AVs-qk0p5m5NCUM8eli8

Podmieniamy tylko pliki exe i działa.
Hasło co najmniej 5 znaków musi mieć
