### ISSUE TITLE
Uciążliwy konstruktor

### ISSUE THREAD

**Issue by Barto-Paja** [Barto-Paja/iDocCar#6]
https://github.com/Barto-Paja/iDocCar/blob/9572e1f8978cd86661349a18d2d51d48ce27508e/sql.cpp#L10

Przy każdym tworzeniu zmiennej w innej klasie należy podawać komplet danych konfiguracyjnych do logowania. Jest to jednak uciążliwe i w razie zmiany należy przepisywać konfigurację w każdej klasie, gdzie została użyta zmienna klasy SQL.

**Comment by RaZoXzU** [comment]
Poprawione
